[2021-08-31 18:41:38,644] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-30T00:00:00+00:00 [queued]>
[2021-08-31 18:41:38,663] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-30T00:00:00+00:00 [queued]>
[2021-08-31 18:41:38,663] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-08-31 18:41:38,664] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-08-31 18:41:38,664] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-08-31 18:41:38,697] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-08-30T00:00:00+00:00
[2021-08-31 18:41:38,703] {standard_task_runner.py:52} INFO - Started process 44359 to run task
[2021-08-31 18:41:38,719] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-08-30T00:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp_pnur1o2', '--error-file', '/tmp/tmpl6200zmd']
[2021-08-31 18:41:38,723] {standard_task_runner.py:77} INFO - Job 34: Subtask is_api_available
[2021-08-31 18:41:38,930] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-08-30T00:00:00+00:00 [running]> on host airflowvm
[2021-08-31 18:41:39,224] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-08-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-30T00:00:00+00:00
[2021-08-31 18:41:39,231] {http.py:101} INFO - Poking: api/
[2021-08-31 18:41:39,253] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-31 18:41:39,262] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-08-31 18:41:39,401] {base.py:243} INFO - Success criteria met. Exiting.
[2021-08-31 18:41:39,405] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210830T000000, start_date=20210831T184138, end_date=20210831T184139
[2021-08-31 18:41:39,470] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-31 18:41:39,503] {local_task_job.py:151} INFO - Task exited with return code 0
