[2021-09-02 14:18:03,387] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.print_es_info 2021-09-02T14:14:39.293944+00:00 [queued]>
[2021-09-02 14:18:04,479] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.print_es_info 2021-09-02T14:14:39.293944+00:00 [queued]>
[2021-09-02 14:18:04,480] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-09-02 14:18:04,481] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-09-02 14:18:04,484] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-09-02 14:18:04,609] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): print_es_info> on 2021-09-02T14:14:39.293944+00:00
[2021-09-02 14:18:04,693] {standard_task_runner.py:52} INFO - Started process 15564 to run task
[2021-09-02 14:18:04,737] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elasticsearch_dag', 'print_es_info', '2021-09-02T14:14:39.293944+00:00', '--job-id', '75', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/elasticsearch_dag.py', '--cfg-path', '/tmp/tmp_ga2cqgz', '--error-file', '/tmp/tmp73c09zmm']
[2021-09-02 14:18:04,738] {standard_task_runner.py:77} INFO - Job 75: Subtask print_es_info
[2021-09-02 14:18:05,539] {logging_mixin.py:104} INFO - Running <TaskInstance: elasticsearch_dag.print_es_info 2021-09-02T14:14:39.293944+00:00 [running]> on host airflowvm
[2021-09-02 14:18:06,088] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2021-09-02T14:14:39.293944+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-09-02T14:14:39.293944+00:00
[2021-09-02 14:18:06,287] {base.py:69} INFO - Using connection to: id: elasticsearch_default. Host: localhost, Port: 9200, Schema: http, Login: None, Password: None, extra: {}
[2021-09-02 14:18:06,288] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/airflow/dags/elasticsearch_dag.py", line 11, in _print_es_info
    hook = ElasticHook()
  File "/home/airflow/airflow/plugins/elasticsearch_plugin/hooks/elastic_hook.py", line 19, in __init__
    self.es = Elasticsearch(hosts,*conn_config)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 203, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
TypeError: 'str' object is not callable
[2021-09-02 14:18:06,335] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=print_es_info, execution_date=20210902T141439, start_date=20210902T141803, end_date=20210902T141806
[2021-09-02 14:18:06,578] {local_task_job.py:151} INFO - Task exited with return code 1
